ALTER TYPE "InstallationEventType" ADD VALUE IF NOT EXISTS 'REPAIR';
ALTER TYPE "InstallationEventType" ADD VALUE IF NOT EXISTS 'RECOVERY';
ALTER TYPE "InstallationEventType" ADD VALUE IF NOT EXISTS 'REFRIGERANT_CHANGE';
